import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <ClerkProvider>
            <html lang="en" className={cn("font-sans", inter.variable)}>
                <body className="min-h-dvh flex flex-col">
                    <Navbar />
                    <Sidebar />
                    {children}
                    <Footer />
                </body>
            </html>
        </ClerkProvider>
    );
}
