import { EligibilityQuestion, Camp } from "@/types/donate";

export const eligibilityQuestions: EligibilityQuestion[] = [
    {
        id: "age",
        label: "Age",
        question: "Are you between 18 and 65 years old?",
        hint: "Most blood banks accept donors aged 18–65. Some allow 16–17 with parental consent.",
        type: "boolean",
        disqualifyIfYes: false,
        disqualifyReason:
            "Donors must be between 18 and 65 years old to donate safely.",
    },
    {
        id: "weight",
        label: "Weight",
        question: "Do you weigh at least 50 kg (110 lbs)?",
        hint: "A minimum weight ensures your body can safely handle the volume drawn.",
        type: "boolean",
        disqualifyIfYes: false,
        disqualifyReason: "Donors must weigh at least 50 kg to donate safely.",
    },
    {
        id: "lastDonation",
        label: "Last donation",
        question: "How long has it been since your last blood donation?",
        hint: "Whole blood donors usually need to wait 3 months between donations.",
        type: "select",
        options: [
            { label: "Never donated before", value: "never" },
            { label: "More than 3 months ago", value: "3m+" },
            { label: "1–3 months ago", value: "1-3m", disqualifies: true },
            {
                label: "Less than 1 month ago",
                value: "<1m",
                disqualifies: true,
            },
        ],
        retryAfterDays: 90,
        disqualifyReason:
            "You need at least 3 months between whole blood donations.",
    },
    {
        id: "recentIllness",
        label: "Recent illness",
        question: "Have you had a fever, flu, or infection in the last 7 days?",
        hint: "You should be symptom-free for at least 7 days before donating.",
        type: "boolean",
        disqualifyIfYes: true,
        retryAfterDays: 7,
        disqualifyReason:
            "You must be symptom-free for at least 7 days before donating.",
    },
    {
        id: "medications",
        label: "Medications",
        question: "Are you currently taking any of these medications?",
        hint: "Some medications (antibiotics, blood thinners, certain acne treatments) temporarily disqualify donors.",
        type: "select",
        options: [
            { label: "None of these", value: "none" },
            { label: "Antibiotics", value: "antibiotics", disqualifies: true },
            { label: "Blood thinners", value: "thinners", disqualifies: true },
            {
                label: "Isotretinoin (Accutane)",
                value: "accutane",
                disqualifies: true,
            },
            { label: "Other prescription meds", value: "other" },
        ],
        retryAfterDays: 30,
        disqualifyReason:
            "Some medications require a waiting period before donating.",
    },
    {
        id: "tattoo",
        label: "Tattoo / piercing",
        question:
            "Have you had a tattoo, piercing, or acupuncture in the last 6 months?",
        hint: "These carry a small infection risk and usually require a 6-month deferral.",
        type: "boolean",
        disqualifyIfYes: true,
        retryAfterDays: 180,
        disqualifyReason:
            "Recent tattoos or piercings require a 6-month waiting period.",
    },
    {
        id: "surgery",
        label: "Surgery",
        question: "Have you had a major surgery in the last 6 months?",
        hint: "Major surgery requires recovery time before donating.",
        type: "boolean",
        disqualifyIfYes: true,
        retryAfterDays: 180,
        disqualifyReason:
            "You need at least 6 months of recovery after major surgery.",
    },
    {
        id: "pregnancy",
        label: "Pregnancy",
        question:
            "Are you currently pregnant or have you given birth in the last 6 months?",
        hint: "Donors who are pregnant or recently gave birth should wait before donating.",
        type: "boolean",
        disqualifyIfYes: true,
        retryAfterDays: 180,
        disqualifyReason:
            "You should wait at least 6 months after giving birth before donating.",
    },
    {
        id: "travel",
        label: "Recent travel",
        question:
            "Have you travelled to a malaria-endemic region in the last 3 months?",
        hint: "Some regions carry malaria or other infection risks that require a deferral.",
        type: "boolean",
        disqualifyIfYes: true,
        retryAfterDays: 90,
        disqualifyReason:
            "Travel to malaria-endemic regions requires a 3-month deferral.",
    },
    {
        id: "chronicConditions",
        label: "Chronic conditions",
        question: "Do you have any of these conditions?",
        hint: "Some chronic conditions may prevent donation. Consult your doctor if unsure.",
        type: "select",
        options: [
            { label: "None of these", value: "none" },
            {
                label: "HIV / Hepatitis B or C",
                value: "hiv-hep",
                disqualifies: true,
            },
            { label: "Active cancer", value: "cancer", disqualifies: true },
            {
                label: "Severe heart disease",
                value: "heart",
                disqualifies: true,
            },
            { label: "Other chronic condition", value: "other" },
        ],
        disqualifyReason:
            "Some chronic conditions prevent blood donation. Please consult your doctor.",
    },
];

export const CITIES = [
    "All cities",
    "South Bombay",
    "Navi Mumbai",
    "Thane",
    "Suburbs",
];

export const BLOOD_TYPES = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const MOCK_CAMPS: Camp[] = [
    {
        id: "camp-001",
        name: "City Blood Bank Drive",
        hospital: "City Blood Bank",
        address: "12 Marine Drive, South Bombay",
        city: "South Bombay",
        date: "2026-09-28",
        startTime: "09:00",
        endTime: "16:00",
        slotsTotal: 40,
        slotsLeft: 14,
        needs: ["A+", "O-"],
    },
    {
        id: "camp-002",
        name: "St. Mary's Hospital Camp",
        hospital: "St. Mary's Hospital",
        address: "45 Colaba Causeway, South Bombay",
        city: "South Bombay",
        date: "2026-09-29",
        startTime: "10:00",
        endTime: "17:00",
        slotsTotal: 30,
        slotsLeft: 22,
        needs: ["B+", "AB+"],
    },
    {
        id: "camp-003",
        name: "Bombay Hospital Donation Drive",
        hospital: "Bombay Hospital",
        address: "12 New Marine Lines, South Bombay",
        city: "South Bombay",
        date: "2026-10-02",
        startTime: "08:30",
        endTime: "15:30",
        slotsTotal: 45,
        slotsLeft: 8,
        needs: ["O+", "O-"],
    },
    {
        id: "camp-004",
        name: "Jaslok Hospital Blood Camp",
        hospital: "Jaslok Hospital",
        address: "15 Dr. G Deshmukh Marg, South Bombay",
        city: "South Bombay",
        date: "2026-10-04",
        startTime: "09:00",
        endTime: "16:00",
        slotsTotal: 35,
        slotsLeft: 20,
        needs: ["A-", "B+"],
    },
    {
        id: "camp-005",
        name: "Grant Medical College Drive",
        hospital: "Grant Medical College",
        address: "J.J. Marg, Byculla, South Bombay",
        city: "South Bombay",
        date: "2026-10-06",
        startTime: "09:30",
        endTime: "15:00",
        slotsTotal: 50,
        slotsLeft: 33,
        needs: ["AB-", "O+"],
    },

    {
        id: "camp-006",
        name: "Red Cross Society Drive",
        hospital: "Red Cross Society",
        address: "8 Palm Beach Rd, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-01",
        startTime: "09:30",
        endTime: "15:30",
        slotsTotal: 50,
        slotsLeft: 7,
        needs: ["O+", "O-", "A-"],
    },
    {
        id: "camp-007",
        name: "Apollo Hospital Camp",
        hospital: "Apollo Hospital",
        address: "Plot 13, Sector 23, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-03",
        startTime: "08:00",
        endTime: "14:00",
        slotsTotal: 60,
        slotsLeft: 40,
        needs: ["A+", "B+", "AB-"],
    },
    {
        id: "camp-008",
        name: "MGM Hospital Blood Drive",
        hospital: "MGM Hospital",
        address: "Sector 20, Kamothe, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-05",
        startTime: "09:00",
        endTime: "16:00",
        slotsTotal: 40,
        slotsLeft: 25,
        needs: ["B-", "O+"],
    },
    {
        id: "camp-009",
        name: "D.Y. Patil Hospital Camp",
        hospital: "D.Y. Patil Hospital",
        address: "Sector 7, Nerul, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-08",
        startTime: "10:00",
        endTime: "17:00",
        slotsTotal: 45,
        slotsLeft: 18,
        needs: ["A+", "A-"],
    },
    {
        id: "camp-010",
        name: "Terna Medical Centre Drive",
        hospital: "Terna Medical Centre",
        address: "Sector 12, Nerul, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-10",
        startTime: "09:00",
        endTime: "15:30",
        slotsTotal: 30,
        slotsLeft: 30,
        needs: ["AB+", "O-"],
    },
    {
        id: "camp-011",
        name: "Vashi Blood Donation Camp",
        hospital: "Vashi General Hospital",
        address: "Sector 17, Vashi, Navi Mumbai",
        city: "Navi Mumbai",
        date: "2026-10-12",
        startTime: "08:30",
        endTime: "14:30",
        slotsTotal: 55,
        slotsLeft: 9,
        needs: ["B+", "O+"],
    },

    {
        id: "camp-012",
        name: "Thane Civil Hospital Drive",
        hospital: "Thane Civil Hospital",
        address: "Dr. Ambedkar Rd, Thane West",
        city: "Thane",
        date: "2026-10-05",
        startTime: "09:00",
        endTime: "16:00",
        slotsTotal: 35,
        slotsLeft: 18,
        needs: ["O+", "A+"],
    },
    {
        id: "camp-013",
        name: "Jupiter Hospital Blood Camp",
        hospital: "Jupiter Hospital",
        address: "Eastern Express Hwy, Thane West",
        city: "Thane",
        date: "2026-10-07",
        startTime: "09:30",
        endTime: "17:00",
        slotsTotal: 40,
        slotsLeft: 12,
        needs: ["A-", "B-"],
    },
    {
        id: "camp-014",
        name: "Hiranandani Hospital Drive",
        hospital: "Hiranandani Hospital",
        address: "Kolshet Rd, Thane West",
        city: "Thane",
        date: "2026-10-09",
        startTime: "10:00",
        endTime: "16:30",
        slotsTotal: 45,
        slotsLeft: 27,
        needs: ["AB+", "O+"],
    },
    {
        id: "camp-015",
        name: "Kaushalya Medical Foundation Camp",
        hospital: "Kaushalya Medical Foundation",
        address: "Panchpakhadi, Thane West",
        city: "Thane",
        date: "2026-10-11",
        startTime: "09:00",
        endTime: "15:00",
        slotsTotal: 30,
        slotsLeft: 5,
        needs: ["O-", "B+"],
    },
    {
        id: "camp-016",
        name: "Aayush Multispeciality Drive",
        hospital: "Aayush Multispeciality",
        address: "Ghodbunder Rd, Thane West",
        city: "Thane",
        date: "2026-10-13",
        startTime: "08:00",
        endTime: "14:00",
        slotsTotal: 50,
        slotsLeft: 38,
        needs: ["A+", "AB-"],
    },
    {
        id: "camp-017",
        name: "Bethany Hospital Blood Camp",
        hospital: "Bethany Hospital",
        address: "Pokhran Rd 2, Thane West",
        city: "Thane",
        date: "2026-10-15",
        startTime: "09:30",
        endTime: "16:00",
        slotsTotal: 35,
        slotsLeft: 21,
        needs: ["B+", "O+"],
    },

    {
        id: "camp-018",
        name: "Fortis Blood Drive",
        hospital: "Fortis Hospital",
        address: "Mulund Goregaon Link Rd, Suburbs",
        city: "Suburbs",
        date: "2026-10-07",
        startTime: "10:00",
        endTime: "17:00",
        slotsTotal: 45,
        slotsLeft: 30,
        needs: ["B-", "AB+"],
    },
    {
        id: "camp-019",
        name: "Lifeline Blood Camp",
        hospital: "Lifeline Hospital",
        address: "SV Rd, Andheri West, Suburbs",
        city: "Suburbs",
        date: "2026-10-09",
        startTime: "09:00",
        endTime: "15:00",
        slotsTotal: 40,
        slotsLeft: 26,
        needs: ["A-", "O+"],
    },
    {
        id: "camp-020",
        name: "Kokilaben Blood Drive",
        hospital: "Kokilaben Hospital",
        address: "Rao Saheb Achutrao Patwardhan Marg, Suburbs",
        city: "Suburbs",
        date: "2026-10-11",
        startTime: "10:00",
        endTime: "16:00",
        slotsTotal: 50,
        slotsLeft: 12,
        needs: ["AB+", "B+"],
    },
    {
        id: "camp-021",
        name: "Lilavati Hospital Camp",
        hospital: "Lilavati Hospital",
        address: "A-791 Bandra Reclamation, Suburbs",
        city: "Suburbs",
        date: "2026-10-13",
        startTime: "09:00",
        endTime: "16:30",
        slotsTotal: 55,
        slotsLeft: 19,
        needs: ["O+", "O-"],
    },
    {
        id: "camp-022",
        name: "Nanavati Hospital Drive",
        hospital: "Nanavati Hospital",
        address: "SV Rd, Vile Parle West, Suburbs",
        city: "Suburbs",
        date: "2026-10-15",
        startTime: "08:30",
        endTime: "15:30",
        slotsTotal: 40,
        slotsLeft: 6,
        needs: ["A+", "B+"],
    },
    {
        id: "camp-023",
        name: "Holy Family Hospital Camp",
        hospital: "Holy Family Hospital",
        address: "St. Andrew's Rd, Bandra West, Suburbs",
        city: "Suburbs",
        date: "2026-10-17",
        startTime: "09:00",
        endTime: "16:00",
        slotsTotal: 35,
        slotsLeft: 24,
        needs: ["AB-", "A-"],
    },
    {
        id: "camp-024",
        name: "Surya Hospital Blood Camp",
        hospital: "Surya Hospital",
        address: "SV Rd, Santacruz West, Suburbs",
        city: "Suburbs",
        date: "2026-10-19",
        startTime: "10:00",
        endTime: "17:00",
        slotsTotal: 45,
        slotsLeft: 35,
        needs: ["B-", "O-"],
    },
];
